version: '2'
services:
    lims-app:
        image: lims
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://lims-mysql:3306/lims?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=lims-elasticsearch:9300
        ports:
            - 8080:8080
    lims-mysql:
        extends:
            file: mysql.yml
            service: lims-mysql
    lims-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: lims-elasticsearch
